name: firebase_ui_oauth_oidc
description: Firebase UI widget for authentication through OAuth2/OIDC providers
version: 0.1.0
homepage: https://github.com/IO-Design-Team/firebase_ui_oauth_oidc

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.1.1
  firebase_ui_oauth: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^4.0.0

