name: firebase_ui_oauth_oidc
description: Firebase UI widget for authentication through OAuth2/OIDC providers
version: 0.2.5
homepage: https://github.com/IO-Design-Team/firebase_ui_oauth_oidc

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.1.1
  firebase_ui_oauth: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^6.0.1
  firebase_core: ^2.3.0
  firebase_ui_auth: ^1.1.0
